#!/bin/bash
#
# Author:  Fábio Berbert de Paula <fberbert at gmail dot com>
# Date:    2023-02-23
# License: GPLv3
# Version: 0.1
#
# This script uses:
#
# - ImageMagick to take a print screen of a screen area
# - tesseract-ocr to extract text from the print screen
# - xsel to copy the extracted text to the clipboard
#
# Dependencies:
# - imagemagick
# - tesseract-ocr
# - xsel
#

# Search the commands
TESSERACT_CMD=$(which tesseract)
IMPORT_CMD=$(which import)  
XSEL_CMD=$(which xsel)

# Verify if dependencies are installed
if [ ! -x $TESSERACT_CMD ]; then
    echo "tesseract-ocr is not installed"
    exit 1
fi

if [ ! -x $IMPORT_CMD ]; then
    echo "imagemagick is not installed"
    exit 1
fi

if [ ! -x $XSEL_CMD ]; then
    echo "xsel is not installed"
    exit 1
fi

IMG_TEMP=/tmp/extract-text-$(date +%s).png

# Take a print screen of the area
$IMPORT_CMD $IMG_TEMP

# Extract text from the print screen
$TESSERACT_CMD $IMG_TEMP stdout | $XSEL_CMD

# Remove the print screen
rm $IMG_TEMP

# Copy the extracted text to the clipboard
$XSEL_CMD -o
