#!/bin/bash
#
# Author:  Fábio Berbert de Paula <fberbert at gmail dot com>
# Date:    2023-02-23
# License: GPLv3
# Version: 0.1
#
# This script uses:
#
# - ImageMagick to take a print screen of a screen area
# - tesseract-ocr to extract text from the print screen
# - xsel to copy the extracted text to the clipboard
#
# Dependencies:
# - imagemagick
# - tesseract-ocr
# - xsel
#

# Dependencies array
DEPENDENCIES=(tesseract import xsel)

# Verify if dependencies are installed
# for each dependency in the array
for DEPENDENCY in ${DEPENDENCIES[@]} ; do
  # if the dependency is not installed
  if [ -z $(which $DEPENDENCY) ] ; then
    # print a message and exit
    echo "$DEPENDENCY not installed. Aborting"
    exit 1
  fi
done

# If all dependencies are installed
# set the commands to variables
TESSERACT_CMD=$(which tesseract)
IMPORT_CMD=$(which import)
XSEL_CMD="$(which xsel) -b"

IMG_TEMP=/tmp/extract-text-$(date +%s).png

# Take a print screen of the area
$IMPORT_CMD $IMG_TEMP

# Extract text from the print screen
# remove multiple blank lines
# and copy the text to the clipboard
$TESSERACT_CMD $IMG_TEMP stdout | sed '/^$/N;/^\n$/D' | $XSEL_CMD

# Remove the print screen
rm $IMG_TEMP

# Copy the extracted text to the clipboard
$XSEL_CMD -o
